#!/bin/bash
version=`python3 -c "import electrum_onion; print(electrum_onion.version.ELECTRUM_VERSION)"`
sig=`./run_electrum -o signmessage $SIGNING_ADDRESS $version -w $SIGNING_WALLET`
echo "{ \"version\":\"$version\", \"signatures\":{ \"$SIGNING_ADDRESS\":\"$sig\"}}"
